name: tbn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - audioread=2.1.6
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.8.28
  - certifi=2019.9.11
  - cffi=1.12.3
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - expat=2.2.6
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libflac=1.3.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libogg=1.3.2
  - libopus=1.3
  - libpng=1.6.37
  - librosa=0.7.0
  - libsndfile=1.0.28
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libvorbis=1.3.6
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.29.0
  - matplotlib=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - numba=0.45.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - openssl=1.1.1d
  - pcre=8.43
  - pillow=5.4.1
  - pip=19.2.3
  - pycparser=2.19
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pysoundfile=0.10.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - pytz=2019.2
  - qt=5.9.7
  - readline=7.0
  - resampy=0.2.2
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.3
  - wheel=0.33.6
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - docopt==0.6.2
    - epic-kitchens==1.7.0
    - gulpio==540.66
    - jinja2==2.10.1
    - markupsafe==1.1.1
    - opencv-python==4.1.1.26
    - pandas==0.25.1
    - protobuf==3.9.2
    - pyyaml==5.1.2
    - sh==1.12.14
    - tensorboardx==1.8
    - tqdm==4.36.1

